language: ruby

sudo: false

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

services:
  - postgresql
addons:
  postgresql: 9.6
before_install: gem install bundler
before_script:
  - psql -c 'create database sequel_plugins;' -U postgres
script:
  - bundle exec rspec
  - bundle exec rubocop

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

cache: bundler
